### PR TITLE
Added a basic submodule level

### PR DESCRIPTION
**Pull request by jackmaney**
Added a basic level for adding a (dummy) submodule. I got `githug test` to pass, but am not sure how to run the integration test (my Ruby-Fu is fairly weak...).

### CODE REVIEW

**Comment by jackmaney** [comment]
Huh... Looks like the Travis CI build failed for Ruby 1.8.7 (but passed for everything else). Unfortunately, the logs don't seem to indicate what's wrong:

```
..Cloning into 'githug-include-me'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 9 (delta 1), reused 0 (delta 0)
Unpacking objects: 100% (9/9), done.
Checking connectivity... done.
F.
Failures:
  1) The Game solves the submodule level
     Failure/Error: `githug`.should be_solved
       expected "********************************************************************************\n*                                    Githug                                    *\n********************************************************************************\n\e[31mSorry, this solution is not quite right!\e[0m\n\nName: submodule\nLevel: 54\nDifficulty: **\n\nYou want to include the files from the following repo: `https://github.com/jackmaney/githug-include-me` into a the folder `./githug-include-me`. Do this without cloning the repo or copying the files from the repo into this repo.\n\nnil\n" to be solved
     # ./spec/githug_spec.rb:303
Finished in 55.78 seconds
129 examples, 1 failure
Failed examples:
rspec ./spec/githug_spec.rb:301 # The Game solves the submodule level
```

Is there any way to get a more detailed log of what's going on?

**Comment by jackmaney** [comment]
Just for the heck of it, I'm gonna close and reopen this to re-trigger a new build.

**Comment by jackmaney** [comment]
Ah ha! [In Ruby 1.8.7, there is no `exist?` method in `Dir`.](http://ruby-doc.org/core-1.8.7/Dir.html) Hmmm.....

**Comment by jackmaney** [comment]
(Rebased to squash second commit into the first commit)

**Comment by Gazler** [comment]
This is amazing. I followed the story all the way though. 10/10 - would merge again.

Thanks for the level, looks great.

**Comment by jackmaney** [comment]
You're more than welcome. :smiley:

**Pull request merged**
