### PR TITLE
Classroom concept, issue #313

### PR DESCRIPTION
**Pull request by odiraneyya**
Let me know if you would like me to improve this solution.

Regards,
Orwa

### CODE REVIEW

**Comment by Gazler** [comment]
Thanks for the suggestion.

I'm happy to keep the Dockerfile and instructions for running the application from docker, I think that's a great idea. I don't think the instructions for teachers are necessary for a README, but if you make a blog post or similar about how you've used it in the classroom I'd happily link to it from the README.

**Comment by odiraneyya** [comment]
> Thanks for the suggestion.
> 
> I'm happy to keep the Dockerfile and instructions for running the application from docker, I think that's a great idea. I don't think the instructions for teachers are necessary for a README, but if you make a blog post or similar about how you've used it in the classroom I'd happily link to it from the README.

**Comment by odiraneyya** [comment]
I removed the teaching instructions and instead linked to my docker hub image, which has the intructions over there (commit [99da6d2](https://github.com/odiraneyya/githug/commit/99da6d278b3a7ad4a9f569ca27d3a4e07641439c))

**Comment by Gazler** [comment]
Thanks <3

**Pull request merged**
